### ISSUE TITLE
请问什么时候能发送图片?

### ISSUE THREAD

**Issue by 173cm36d** [chuchenyl/mirai-epl#1]
请问什么时候能发送图片?

**Comment by Novices666** [comment]
有需求就增加，我抽时间添加，请持续关注

**Comment by 173cm36d** [comment]
> 有需求就增加，我抽时间添加，请持续关注

好的，我不太会用github…
我现在在用mirai-epl做CakeGame插件的Mirai接口，有几个使用插件的需要可以发送图片的功能，作者大大有空的话加一下吧

**Comment by Novices666** [comment]
已添加发送图片功能，感谢支持

**Comment by 173cm36d** [comment]
> 已添加发送图片功能，感谢支持

作者大大666

**Comment by 173cm36d** [comment]
> 已添加发送图片功能，感谢支持

噗,只能网络图片url不太行..
因为是大型文字游戏插件,插件会做出本地图片...
然后图床方面我也搞不太懂...作者大大有没有办法支持下本地图片?

**Comment by Novices666** [comment]
> 

你是运行在本地，还是运行在服务器，本地的话可以增加，在服务器的话，因为项目依赖的mirai-api-http的媒体上传接口还没有，本项目自然就不支持了

**Comment by 173cm36d** [comment]
> > 
> 
> 你是运行在本地，还是运行在服务器，本地的话可以增加，在服务器的话，因为项目依赖的mirai-api-http的媒体上传接口还没有，本项目自然就不支持了

本地和服务器都有，大多是在本地运行的

**Comment by Novices666** [comment]
> > > 
> > 
> > 
> > 你是运行在本地，还是运行在服务器，本地的话可以增加，在服务器的话，因为项目依赖的mirai-api-http的媒体上传接口还没有，本项目自然就不支持了
> 
> 本地和服务器都有，大多是在本地运行的

好的，我尽量满足，可能需要点时间去处理服务器上传的问题，本地的会抽时间尽快安排，不过如果你服务器是windows系统的话，那就和本地是没区别的了

**Comment by 173cm36d** [comment]
> > > > 
> > > 
> > > 
> > > 你是运行在本地，还是运行在服务器，本地的话可以增加，在服务器的话，因为项目依赖的mirai-api-http的媒体上传接口还没有，本项目自然就不支持了
> > 
> > 
> > 本地和服务器都有，大多是在本地运行的
> 
> 好的，我尽量满足，可能需要点时间去处理服务器上传的问题，本地的会抽时间尽快安排，不过如果你服务器是windows系统的话，那就和本地是没区别的了

那应该没问题，谢谢作者大大！

**Comment by Novices666** [comment]
已添加发送本地图片

**Comment by 173cm36d** [comment]
多谢大佬!
