### ISSUE TITLE
请求教程

### ISSUE THREAD

**Issue by hlfzsi** [chuchenyl/mirai-epl#2]
请问能否提供一个简单插件的代码示例

**Comment by Novices666** [comment]
你好，直接下载下来就可以了。没有插件化，代码只是对mirai-http的部分功能的实现，可以作为参考例程。您在创建自己的项目时，可以参考本项目的写法。



---Original---
From: ***@***.***&gt;
Sent at: 2023年7月29日(Sat) PM2:48
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Novices666/mirai-epl] 请求教程 (Issue #2)




 
请问能否提供一个简单插件的代码示例

**Comment by Novices666** [comment]
简单功能的实现，目前还没有时间去重构项目，后续有时间会进行重构，然后提供相关代码示例。
本程序在构建初期存在大量结构问题，导致后续的更新只能在原有的基础上继续加入更多有问题的代码。
就目前来说，本项目只是对mirai-http相关方法的实现，。您开发时可以参考，或者是在本项目的基础上进行开发。

开发需要用到相关的功能时，请直接调用方法即可！

感谢您对本项目的关注。如有其他问题，请重新打开此issues

重构时间应该在2024.06前！
