### ISSUE TITLE
我使用您的易语言源码，直接不能连接到mirai

### ISSUE THREAD

**Issue by PigZou** [chuchenyl/mirai-epl#3]
状态条1.置文本 (1, ws_连接_远程 (“192.168.123.96”, “8080”, “1987041700”, “1719017190”, &消息处理))
无法连接成功

**Comment by Novices666** [comment]
已收到您的反馈，我抽时间尽快去排查下，处理后会对仓库代码进行更新。



---Original---
From: ***@***.***&gt;
Sent at: 2023年8月3日(Thu) Noon1:31
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Novices666/mirai-epl] 我使用您的易语言源码，直接不能连接到mirai (Issue #3)




 
状态条1.置文本 (1, ws_连接_远程 (“192.168.123.96”, “8080”, “1987041700”, “1719017190”, &amp;消息处理))
 无法连接成功

**Comment by Novices666** [comment]
目前来看程序没问题。
1.应该使用本地连接
2.使用远程连接本地，需要在地址栏填写127.0.0.1或者localhost
3.请确保mcl已经登录了对应的qq，且相关的端口号，key正确。
-----------------------------
如还有问题，请重新开启本issues。



---Original---
From: ***@***.***&gt;
Sent at: 2023年8月3日(Thu) Noon1:31
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Novices666/mirai-epl] 我使用您的易语言源码，直接不能连接到mirai (Issue #3)




 
状态条1.置文本 (1, ws_连接_远程 (“192.168.123.96”, “8080”, “1987041700”, “1719017190”, &amp;消息处理))
 无法连接成功

**Comment by PigZou** [comment]
错误(10041): 调用子程序“ws_连接_本地”时传递了过多的参数。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Novices666/mirai-epl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月4日(星期五) 下午3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Novices666/mirai-epl] 我使用您的易语言源码，直接不能连接到mirai (Issue #3)





 目前来看程序没问题。 
 1.应该使用本地连接 
 2.使用远程连接本地，需要在地址栏填写127.0.0.1或者localhost 
 3.请确保mcl已经登录了对应的qq，且相关的端口号，key正确。 
 ----------------------------- 
 如还有问题，请重新开启本issues。 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Sent at: 2023年8月3日(Thu) Noon1:31 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.***&amp;gt;; 
 Subject: [Novices666/mirai-epl] 我使用您的易语言源码，直接不能连接到mirai (Issue #3) 
 
 
 
 
   
 状态条1.置文本 (1, ws_连接_远程 (“192.168.123.96”, “8080”, “1987041700”, “1719017190”, &amp;amp;消息处理)) 
  无法连接成功

**Comment by Novices666** [comment]
您仔细看下参数！
可以到对应的代码处阅读下。
处理报错是每个开发者必备的一项技能。
希望之后不要再提问这样低级的错误了。



---Original---
From: ***@***.***&gt;
Sent at: 2023年8月4日(Fri) PM4:42
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Novices666/mirai-epl] 我使用您的易语言源码，直接不能连接到mirai (Issue #3)




 错误(10041): 调用子程序“ws_连接_本地”时传递了过多的参数。 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Novices666/mirai-epl"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年8月4日(星期五) 下午3:53 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Novices666/mirai-epl] 我使用您的易语言源码，直接不能连接到mirai (Issue #3) 
 
 
 
 
 
  目前来看程序没问题。  
  1.应该使用本地连接  
  2.使用远程连接本地，需要在地址栏填写127.0.0.1或者localhost  
  3.请确保mcl已经登录了对应的qq，且相关的端口号，key正确。  
  -----------------------------  
  如还有问题，请重新开启本issues。  
   
   
   
  ---Original---  
  From: ***@***.***&amp;amp;gt;  
  Sent at: 2023年8月3日(Thu) Noon1:31  
  To: ***@***.***&amp;amp;gt;;  
  Cc: ***@***.***&amp;amp;gt;;  
  Subject: [Novices666/mirai-epl] 我使用您的易语言源码，直接不能连接到mirai (Issue #3)  
   
   
   
   
     
  状态条1.置文本 (1, ws_连接_远程 (“192.168.123.96”, “8080”, “1987041700”, “1719017190”, &amp;amp;amp;消息处理))  
   无法连接成功
